apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  FLARUM_ADMIN_USER: "{{ .Values.config.user }}"
  FLARUM_ADMIN_PASS: "{{ .Values.config.pass }}"
  FLARUM_ADMIN_MAIL: "{{ .Values.config.mail }}"
  FLARUM_TITLE: "{{ .Values.config.title }}"
  DB_PASS: "{{ .Values.mariadb.auth.password }}"
  DB_NAME: "{{ .Values.mariadb.auth.database }}"
  DB_USER: "{{ .Values.mariadb.auth.username }}"
  DB_HOST: "{{ .Values.mariadb.fullnameOverride }}"
  FORUM_URL: "https://{{ .Values.ingress.hostname }}/"