apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  FLARUM_ADMIN_USER: "{{ .Values.config.user }}"
  FLARUM_ADMIN_PASS: "{{ .Values.config.pass }}"
  FLARUM_ADMIN_MAIL: "{{ .Values.config.mail }}"
  FLARUM_TITLE: "{{ .Values.config.title }}"